// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Slider.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
public:
  Fl_Value_Slider *BrightnessSlider;
private:
  inline void cb_BrightnessSlider_i(Fl_Value_Slider*, void*);
  static void cb_BrightnessSlider(Fl_Value_Slider*, void*);
  inline void cb_Edge_i(Fl_Button*, void*);
  static void cb_Edge(Fl_Button*, void*);
  inline void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  inline void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
  inline void cb_L_i(Fl_Button*, void*);
  static void cb_L(Fl_Button*, void*);
  inline void cb_R_i(Fl_Button*, void*);
  static void cb_R(Fl_Button*, void*);
  inline void cb_U_i(Fl_Button*, void*);
  static void cb_U(Fl_Button*, void*);
  inline void cb_D_i(Fl_Button*, void*);
  static void cb_D(Fl_Button*, void*);
  inline void cb_Tilt_i(Fl_Button*, void*);
  static void cb_Tilt(Fl_Button*, void*);
  inline void cb_Pan_i(Fl_Button*, void*);
  static void cb_Pan(Fl_Button*, void*);
  inline void cb_Roll_i(Fl_Button*, void*);
  static void cb_Roll(Fl_Button*, void*);
  inline void cb_Load1_i(Fl_Button*, void*);
  static void cb_Load1(Fl_Button*, void*);
public:
  Fl_Value_Slider *ContrastSlider;
private:
  inline void cb_ContrastSlider_i(Fl_Value_Slider*, void*);
  static void cb_ContrastSlider(Fl_Value_Slider*, void*);
public:
  void show();
  void DBG_cb();
  void load_cb();
  void save_cb();
  void brightness_cb();
  void detect_edges_cb();
  void load_geometry_cb();
  void left_cb();
  void right_cb();
  void down_cb();
  void tilt_cb();
  void pan_cb();
  void roll_cb();
  void up_cb();
  void contrast_cb();
};
#endif
