// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Slider.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
public:
  Fl_Check_Button *FlagB;
private:
  inline void cb_FlagB_i(Fl_Check_Button*, void*);
  static void cb_FlagB(Fl_Check_Button*, void*);
public:
  Fl_Value_Slider *BrightnessSlider;
private:
  inline void cb_BrightnessSlider_i(Fl_Value_Slider*, void*);
  static void cb_BrightnessSlider(Fl_Value_Slider*, void*);
  inline void cb_Edge_i(Fl_Button*, void*);
  static void cb_Edge(Fl_Button*, void*);
  inline void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  inline void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void FlagB_cb();
  void load_cb();
  void save_cb();
  void brightness_cb();
  void detect_edges_cb();
};
#endif
